### ISSUE TITLE
Trouble Installing Spotify Controls

### ISSUE THREAD

**Issue by cweisel** [phpfunk/alfred-spotify-controls#1]
I'm running Alfred 0.9.10 (152) on Lion, and downloaded Spotify Controls today from the Dropbox download link. I open the file with Alfred to install it, but it doesn't seem to be working. "spot" doesn't appear to be a command, and there is nothing in the preferences that it is installed (I can't actually find any place where the extensions are installed). 

Help? Please let me know if you need any more information.

**Comment by cweisel** [comment]
My bad, I didn't RTFM. I need the Power Pack, which I don't have. Sorry.

**Comment by phpfunk** [comment]
Hey no problem, I highly recommend the power pack. Alfredapp is killer.
