### ISSUE TITLE
Completion for commands in alfred

### ISSUE THREAD

**Issue by wraithan** [phpfunk/alfred-spotify-controls#10]
Not sure if this is a limitation because of alfred of because of your script (have not looked into either too closely) but having all the spot commands listed after typing `spot` would be neat.

**Comment by shreve** [comment]
How do you mean, listed? Like in the description?
http://cloud.shreve.ly/image/1o111U0L0E21

**Comment by phpfunk** [comment]
Hey this will be fixed in Version 2 when Alfred 2 comes out. Workflows allow a lot more flexibility and I have already updated this here: https://github.com/phpfunk/alfred-spotify-controls/tree/v2
