### ISSUE TITLE
Support for Mountain Lion desktop notifications

### ISSUE THREAD

**Issue by OliverJAsh** [phpfunk/alfred-spotify-controls#12]
If Growl support is not there…

**Comment by DanielSiepmann** [comment]
Or if you don't like Growl anymore, because there are the built in notification. +1

**Comment by phpfunk** [comment]
I will see if I can rewrite in shell. Currently there is no real applescript support for ML notifications.

**Comment by phpfunk** [comment]
This is version 2 of the extension. You will have to wait for public release of alfred version 2 though. Closing this.

https://github.com/phpfunk/alfred-spotify-controls/tree/v2
