### ISSUE TITLE
Changing "spot" to "sp" for new Alfred 2 based workflow

### ISSUE THREAD

**Issue by bradical** [phpfunk/alfred-spotify-controls#15]
More of a question than an issue really.

Is it possible to do a bulk change of all the commands in the workflow to use "sp" instead of "spot"? I tried to edit the .alfredworkflow file but it's binary.

Great tool by the way.

Thanks!

**Comment by AlecRust** [comment]
I agree, 4 characters does seem a little excessive to type each time.

**Comment by bradical** [comment]
And to be clear, you can definitely change this already by going in and editing each input in the workflow. I'm just looking for a quick and easy way of bulk changing them or changing them before I install it.

**Comment by phpfunk** [comment]
I don't think there is a bulk way to do it in workflows. You will have to edit spot to sp in each command.

**Comment by mmemetea** [comment]
Open the info.plist and search/replace all occurences of <string>spot by <string>sp.
(Sublime Text and CTRL+CMD+G are good too).
Worked for me

**Comment by phpfunk** [comment]
Ah, good call. Thanks for the tip!

**Comment by bradical** [comment]
Nice, thanks!
