### ISSUE TITLE
Toggling between play and pause in Alfred 2 workflow

### ISSUE THREAD

**Issue by bradical** [phpfunk/alfred-spotify-controls#16]
Another feature I really liked in the older version was the ability to toggle between play/pause without having to type those commands.

I had it mapped to "sp" so I would just use "sp" to toggle between play/pause. Is this possible in the v2 workflow?

**Comment by phpfunk** [comment]
Will take a look.

**Comment by bradical** [comment]
I found a solution for this: just train Alfred to always use the "Play" option by default when you type "sp" (or whatever your Spotify keyword is). That way, when I type "sp" it default to Spotify Play and that toggles between play/pause.
