### ISSUE TITLE
Support for controlling rand/repeat

### ISSUE THREAD

**Issue by aidabeorn** [phpfunk/alfred-spotify-controls#18]
I'd love to see support for controlling rand/repeat modes from the alfred interface.
eg. spot rand to toggle rand option.

**Comment by phpfunk** [comment]
Random and repeat toggle already exist in both versions. You should be able to just type: spot repeat and spot shuffle will toggle them for you.

Do these not work for you?

**Comment by aidabeorn** [comment]
I guess I was just looking for the wrong command :) (maybe add an alias for random -> shuffle?)
Tho repeat doesn't seem to work correctly. (using alfred 2 and v2 branch)

**Comment by phpfunk** [comment]
What does repeat do for  you? Toggles repeat on and off for me. If not let me know what happens and what version of spotify you are using.

**Comment by aidabeorn** [comment]
I only get a growl/notification center "message" that is empty, spotify doesn't switch modes at all.

0.8.8.348.ge445f5b9 is my spotify version

ps. tried commenting out the if clause if it is enabled:
#if repating enabled is true then
....
#else
#return "Repating is not currently enabled."
#end if

then it toggles it.

**Comment by phpfunk** [comment]
ok, are you using version 1 of the extension? sorry I should have asked before. Either way I will take a look.

**Comment by aidabeorn** [comment]
I'm using V2 from git.

**Comment by phpfunk** [comment]
I see the error: if repating enabled is true then `repating` should be `repeating`. Just fixed this up and pushed to master branch. It is version 2.1.9. Thanks for finding this.
