### ISSUE TITLE
Thumbs up, thumbs down

### ISSUE THREAD

**Issue by frankstallone** [phpfunk/alfred-spotify-controls#19]
Feature Request: Not sure how to make one officially flagged as a feature request however I would love to see a 'spot up' or 'spot ^' to thumb up tracks in radio stations; also 'spot down' to thumb down.

**Comment by tudalex** [comment]
:+1:

**Comment by phpfunk** [comment]
I will see if this can be implemented. Will check their updated AS library as well if I can do this from their spotify url structure.

**Comment by frankstallone** [comment]
Thank you, that would be fantastic! I love me some keyboard shortcuts. ;')

On Sat, Jun 15, 2013 at 1:59 PM, Jeff Johns notifications@github.comwrote:

> I will see if this can be implemented. Will check their updated AS library
> as well if I can do this from their spotify url structure.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/phpfunk/alfred-spotify-controls/issues/19#issuecomment-19500613
> .

## 

---

Frank Stallone III
iamfrankstallone.com
twitter.com/frankstallone

**Comment by dsasaki** [comment]
Agreed  — would really love this!

**Comment by kristjan** [comment]
+1

**Comment by ozanozen** [comment]
+1

**Comment by systembell** [comment]
+1

**Comment by jdsmith2816** [comment]
+1
