### ISSUE TITLE
Search syntax pretty verbose

### ISSUE THREAD

**Issue by jpvelez** [phpfunk/alfred-spotify-controls#20]
Awesome job!

Searching for music strikes me as the core use case of this extension since the Spotify search experience isn't great.

But the search syntax is a bit verbose. Could you condense "spot search artist <artist_name>" to "spot artist <artist_name"? 

Is there any way to manually set this?

**Comment by phpfunk** [comment]
This is a good idea, sorry just making it back to all these requests. I have updated the extension to allow this. You can pull the master branch or from tag 2.2.0 - https://github.com/phpfunk/alfred-spotify-controls/tree/2.2.0. Thanks for the suggestion.
