### ISSUE TITLE
Doesn't work with PHP 5.4

### ISSUE THREAD

**Issue by 0x46616c6b** [phpfunk/alfred-spotify-controls#22]
The plugin doesn't return any response when I use PHP 5.4 from macports.

ls -l /usr/bin/php*

```
lrwxr-xr-x  1 root  wheel  20 27 Apr 19:13 /usr/bin/php -> /opt/local/bin/php54
-rwxr-xr-x  1 root  wheel  10992240 21 Sep  2012 /usr/bin/php.bak
```

After returning to PHP built-in from OSX it works fine.

**Comment by phpfunk** [comment]
I will have to test this, I don't have 5.4 installed locally ATM, just the built-in from os-x. Any errors in console you can share?
