### ISSUE TITLE
"spot search" doesn't seem to work

### ISSUE THREAD

**Issue by sethgoldin** [phpfunk/alfred-spotify-controls#23]
Hi, this might be user error on my part, but when I try to type "spot search," followed by a space, the workflow doesn't recognize "album," "artist," or "track." It just loads Alfred's default fallback results. Is there something I'm missing? Please help! The other features seem to work well.
![screen shot 2013-06-06 at 1 46 57 pm](https://f.cloud.github.com/assets/4632977/619587/2287e780-ced1-11e2-9cc2-b4cef38c801a.png)

**Comment by phpfunk** [comment]
Sometimes this happens for a split second. Does it not work when you start to type an album name? Also just pushed a new version to simply search by typing just: spot album {ALBUM}, spot artist {ARTIST} and spot track {TRACK}.

**Comment by sethgoldin** [comment]
Oh wow, it does work! I stopped typing once I saw the fallback searches, but it does work if you continue to type something else. Thanks for the new version as well!

**Comment by jrhorn424** [comment]
Thanks for the info. I didn't find that very intuitive, but I was misreading the help text.

**Comment by phpfunk** [comment]
The newest version uses a hotkey and then you can just type 'artist ARTIST NAME'.

**Comment by sethgoldin** [comment]
This is awesome, thank you!

**Comment by sethgoldin** [comment]
Hey Jeff, this seems to be happening again. I'm not sure what has changed. When I type "spot search", everything seems to be registering, but then when I type an actual artist name, it defaults to the fallback searches. I wait a few seconds, to no avail. Any ideas?

![screen shot 2014-03-05 at 1 40 49 pm](https://f.cloud.github.com/assets/4632977/2336898/054e4312-a496-11e3-993c-b077e5c8c0e5.png)
![screen shot 2014-03-05 at 1 41 02 pm](https://f.cloud.github.com/assets/4632977/2336900/07554b92-a496-11e3-88b4-bdcdfd558aa9.png)

**Comment by jrhorn424** [comment]
Sorry, I stopped using the workflow. Did you try typing `spot search artist rolling stones` and `spot artist rolling stones`?

**Comment by sethgoldin** [comment]
Yeah, I thought the new, updated workflow didn't require the extra modifier after `search`, but `spot search artist rolling stones` does seem to work. Thanks!

**Comment by phpfunk** [comment]
FYI. There is a HOTKEY (default it's command+enter) that will bring up search, where you just type 'artist or album or title then you query' -- artist rolling stones. -- https://github.com/phpfunk/alfred-spotify-controls/wiki/Searching

**Comment by sethgoldin** [comment]
Excellent, didn't know about this. Thanks!
