### ISSUE TITLE
Dies when Growl is not installed

### ISSUE THREAD

**Issue by benui-dev** [phpfunk/alfred-spotify-controls#3]
I do not use Growl, and the plugin does not work when Growl is not installed:

04/01/2012 18:04:05.960 Alfred: [ERROR] AppleScript Error: {
    NSAppleScriptErrorBriefMessage = "Can\U2019t get application id \"com.Growl.GrowlHelperApp\".";
    NSAppleScriptErrorMessage = "Can\U2019t get application id \"com.Growl.GrowlHelperApp\".";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {0, 0}";
}

Could you make the Growl stuff optional?
For now I've just commented out the Growl stuff and it works OK.

**Comment by phpfunk** [comment]
Thanks, will take a look at this. Sorry for the delay in responding.

**Comment by phpfunk** [comment]
This should be fixed now. If not please reopen.
