### ISSUE TITLE
Spotify 1.0.1.1060.gc75ebdfd breaks alfred-spotify-controls

### ISSUE THREAD

**Issue by kyleshevlin** [phpfunk/alfred-spotify-controls#34]
Just upgraded Spotify and it appears that none of the keyword workflows work. I upgraded the workflow with no luck.

Commands I have tried (and errors if shown):
spot play
spot pause
spot next
spot prev
spot track
spot mute
spot vol 60 (no command found)
spot volume 60 (60 must be between 1 - 100)

OS: Yosemite 10.10.2 (14C109)
Spotify version: 1.0.1.1060.gc75ebdfd
Alfred Spotify Controls version - 2.2.10

**Comment by bradical** [comment]
Bummer. @phpfunk are you using this script yourself anymore or have you switched over to any of the ones that descended from yours like Spotifious?

**Comment by brianrhea** [comment]
Yep. I noticed this as well and came here hoping to find a fix. Unfortunately, it looks like the latest version of Spotify has [removed AppleScript support](https://community.spotify.com/t5/Help-Desktop-Linux-Mac-and/New-Mac-Update-AppleScript-support-removed/m-p/995843#M104799).

**Comment by phpfunk** [comment]
I haven't used Spotify in a few years, just been updating the workflow as needed. This is truely a bummer to hear. I don't think there will be a way to implement easily with no AppleScript support in Spotify.

**Comment by kyleshevlin** [comment]
Sad day. Thanks for hunting that down @brianrhea.

**Comment by bradical** [comment]
@phpfunk thanks for supporting this script for the past few years.

@kyleshevlin just a heads up that it looks like a lot of the descendants of this script like [Spotifious](http://www.alfredforum.com/topic/1644-spotifious-a-natural-spotify-controller-for-alfred/) also made use of AppleScript.

Anyone know of any others that don't?

**Comment by lednine** [comment]
It's glitch in .plist, it's easily fixable before official fix. Just right click spotify.app and select show contents, and use text editor..

Just change:
    <key>NSAppleScriptEnabled</key>
    <true/>
    <key>OSAScriptingDefinition</key>
    <string>Spotify.sdef</string>
to:
    <key>NSAppleScriptEnabled</key>
    <true/>
    <key>OSAScriptingDefinition</key>
    <string>applescript/Spotify.sdef</string>

**Comment by bradical** [comment]
Yep, that did the trick for me. Thanks!!

**Comment by kyleshevlin** [comment]
Worked for me too. Thanks for finding that @lednine!

**Comment by bradical** [comment]
Doh, I think this broke again in `1.0.2.6.g9977a14b` and [applying the change to the Info.plist](https://github.com/phpfunk/alfred-spotify-controls/issues/34#issuecomment-79045768) didn't work this time. Anyone else have any luck?

**Comment by kyleshevlin** [comment]
Auto-update screwed me, too. No longer working.

**Comment by bradical** [comment]
Quit both Alfred and Spotify. Apply the fix. Restart both programs.

It didn't work for me until I restarted Alfred.

**Comment by kyleshevlin** [comment]
That worked for me. Thanks.
