### ISSUE TITLE
AppleScript error when running spot commands

### ISSUE THREAD

**Issue by wmccracken** [phpfunk/alfred-spotify-controls#4]
1/11/12 2:48:51.038 PM Alfred: [ERROR] AppleScript Error: {
    NSAppleScriptErrorBriefMessage = "Expected class name but found identifier.";
    NSAppleScriptErrorMessage = "Expected class name but found identifier.";
    NSAppleScriptErrorNumber = "-2741";
    NSAppleScriptErrorRange = "NSRange: {1753, 7}";
}

Alfred 1.0 (179), version of spotify controls 18fa042

**Comment by phpfunk** [comment]
Do you have growl installed on your machine?

**Comment by wmccracken** [comment]
Hi Jeff,

I do - the latest version.

Thanks,

Will

**Comment by phpfunk** [comment]
Thanks. Let me look into this error, I haven't seen it yet.

**Comment by wmccracken** [comment]
Let me know if there is anything that I can do to assist. Thanks!

On Thu, Jan 12, 2012 at 7:12 AM, Jeff Johns <
reply@reply.github.com

**Comment by phpfunk** [comment]
Looking at this again tonight. Silly question but if you open Applescript Editor, go to File > Open Dictionary and let me know if the Spotify.app is listed there. Just want to make sure.

**Comment by phpfunk** [comment]
Also removed a log call, saw a simliar issue online and removing the log call seemed to fix the issue for whatever reason. The latest w/o log call is here: https://github.com/phpfunk/alfred-spotify-controls/zipball/1.3.5

**Comment by wmccracken** [comment]
Hi - the Spotify.app is listed in the Applescript Editor Dictionary.

**Comment by phpfunk** [comment]
I pushed a few minor tweaks the other night. Have you tried downloading the above and re-installing?

**Comment by wmccracken** [comment]
Hi Jeff,

I just installed the update and it looks like it is working! Thanks for the
help.

-Will

On Wed, Mar 28, 2012 at 9:59 PM, Jeff Johns <
reply@reply.github.com

**Comment by phpfunk** [comment]
Great news. I think somehow the log method was messing this up for some reason. Very glad everything is working.
