### ISSUE TITLE
Script does not work if Growl is missing

### ISSUE THREAD

**Issue by tylerjohnst** [phpfunk/alfred-spotify-controls#7]
Error appears in Console.app when you try to issue a command without Growl installed.

```
5/31/12 12:35:06.730 PM Alfred: [ERROR] AppleScript Error: {
    NSAppleScriptErrorBriefMessage = "Can\U2019t get application id \"com.Growl.GrowlHelperApp\".";
    NSAppleScriptErrorMessage = "Can\U2019t get application id \"com.Growl.GrowlHelperApp\".";
    NSAppleScriptErrorNumber = "-1728";
    NSAppleScriptErrorRange = "NSRange: {0, 0}";
}
```

**Comment by phpfunk** [comment]
What version of OS X are you on?

**Comment by tylerjohnst** [comment]
10.7.4

Installing Growl did resolve the issue, though. :)

**Comment by phpfunk** [comment]
Okay, thanks. I need to look into this. I thought the last update for Growl would suffice, but I guess not. Thanks for letting me know.

**Comment by pjaspers** [comment]
Easiest way to fix would be something like this:

``` applescript
        set myApp to "GrowlHelperApp"
        tell application id myApp
        end tell
```

**Comment by phpfunk** [comment]
Thanks, will implement this, this week.

**Comment by tommoor** [comment]
I've been wondering why the controls stopped working! Would be great if this could work without the need for Growl :-)

**Comment by phpfunk** [comment]
Just to update, looking at this tonight.

**Comment by phpfunk** [comment]
I just sent an update that seemed to work locally. Update if isRunning then to if isRunning is true then. Check out the latest code or download version 1.3.7 and let me know if it works for you. If not I will go a different route.

**Comment by phpfunk** [comment]
Scratch that sorry. Don't do that. Back at it.

**Comment by phpfunk** [comment]
Added a new version of the extension with all growl info stripped out. Please download that extension to use with no growl installed. Looking at rewriting this to work with both but wanted to have something for folks with no growl installed now. This can be found at tag 1.3.8 or current master branch as of july 24, 2012.

**Comment by tommoor** [comment]
Jeff,

Just downloaded and tested - works perfectly, thanks for speedy update!

**Comment by phpfunk** [comment]
Fantastic. I will further optimize to bring this back to one extension. Just wanted to get you something that works now.
